# Generated by Django 4.1.2 on 2022-11-21 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_room_remove_text_friends_name_remove_text_my_name_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='friend_img',
        ),
    ]
