# Generated by Django 4.1.2 on 2022-11-23 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_remove_room_friend_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='friend_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='friend_username_friend', to='myapp.signup'),
        ),
        migrations.AlterField(
            model_name='room',
            name='my_username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='my_username_my', to='myapp.signup'),
        ),
    ]
