# Generated by Django 4.1.2 on 2022-11-23 14:33

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_alter_room_friend_username_alter_room_my_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='room',
            name='datetime',
            field=models.DateTimeField(blank=True, default=django.utils.timezone.now, null=True),
        ),
        migrations.AlterField(
            model_name='room',
            name='friend_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_username_friend', to='myapp.signup'),
        ),
        migrations.AlterField(
            model_name='room',
            name='my_username',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_username_my', to='myapp.signup'),
        ),
    ]
