# Generated by Django 4.1.2 on 2022-11-24 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0005_alter_room_datetime_alter_room_friend_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.FileField(default='images/noimage.png', upload_to='img'),
        ),
    ]
