# Generated by Django 4.1.2 on 2022-11-25 12:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0007_alter_signup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.FileField(default='images/noimage.png', upload_to='img'),
        ),
    ]
