# Generated by Django 4.1.2 on 2022-11-25 12:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0008_alter_signup_img'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.FileField(upload_to='img'),
        ),
    ]
