# Generated by Django 4.1.2 on 2022-12-16 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0012_alter_room_friend_username_alter_room_my_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='img',
            field=models.FileField(default='myapp/static/myapp/img/people-24px.svg', upload_to='img'),
        ),
    ]
