# Generated by Django 4.1.2 on 2022-12-16 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0013_alter_signup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='room',
            name='friend_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='friend_img', to='myapp.signup'),
        ),
        migrations.AddField(
            model_name='room',
            name='my_img',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='my_img', to='myapp.signup'),
        ),
    ]
