# Generated by Django 4.1.2 on 2022-12-22 08:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0018_alter_signup_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='signup',
            name='profile',
            field=models.CharField(blank=True, max_length=140, null=True),
        ),
    ]
