# Generated by Django 4.1.2 on 2022-12-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0019_signup_profile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='signup',
            name='status_message',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
